### ISSUE TITLE
You can jump over empty spaces

### ISSUE THREAD

**Issue by j201** [sunjay/peg-solitaire#1]
![sunjaybug](https://cloud.githubusercontent.com/assets/4549370/7193639/b1ba7fa0-e471-11e4-8f28-d292e4823556.gif)

This makes it really easy to win. Harder would not be impressed.

**Comment by sunjay** [comment]
This is a feature, not a bug. I made that design decision explicitly. Are there any official rules for this game? I can disable that too.

**Comment by sunjay** [comment]
Love the gif by the way. 10/10

**Comment by sunjay** [comment]
Fixed in b6ace805e7f4bfd39295eeb62b785bc624be02e3

Thanks j201.
